version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ehr_postgres
    restart: always
    environment:
      POSTGRES_USER: ehr_user
      POSTGRES_PASSWORD: ehr_password
      POSTGRES_DB: ehr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Auto-runs SQL on first start

volumes:
  postgres_data:
    driver: local
